// Types for the read-only question bank JSON (data/questions/*.json).
// The question bank is static and generated by scripts/extract_question_bank.py;
// application code must never write to it (ADR-0002).

export type Letter = "A" | "B" | "C" | "D";

export interface Question {
  number: number; // 101-200 (original book numbering)
  stem: string;
  options: Record<Letter, string>;
  answer: Letter;
  translation: string;
  explanation: string;
}

export interface PassageSet {
  id: string;
  descriptor: string; // e.g. "letter", "advertisement and e-mail message"
  title: string;
  text: string; // combined body (double/triple passages kept as one text)
  questions: Question[];
}

export interface Part5 {
  part: 5;
  questions: Question[];
}

export interface Part6Or7 {
  part: 6 | 7;
  passages: PassageSet[];
}

export type Part = Part5 | Part6Or7;

export interface ReadingTest {
  testId: string; // "reading-01"
  title: string;
  verified: boolean;
  parts: Part[];
}

// ---- dynamic layer (SQLite) ----

export type TestStatus = "not_started" | "seen" | "first_attempted";

export type AttemptType = "practice" | "timed";

export interface Attempt {
  id: number;
  type: AttemptType;
  testId: string;
  startedAt: string; // ISO
  endedAt: string | null;
  durationSec: number | null;
  isFirst: 0 | 1;
  isUnseenSample: 0 | 1;
  accuracy: number | null; // correct / 100
  correct: number | null;
  wrong: number | null;
  unanswered: number | null;
}

export type ErrorPattern = "G" | "V" | "S" | "E" | "T" | "A" | "L" | "K";

export const ERROR_PATTERNS: Record<ErrorPattern, string> = {
  G: "语法知识",
  V: "词汇搭配",
  S: "句法解析",
  E: "证据定位",
  T: "时间策略",
  A: "注意操作",
  L: "听觉加工",
  K: "材料问题",
};

export type RetestSlot = "D+2" | "D+7" | "D+21";
