// Pure helpers over the question bank (client-safe: no node:fs). The disk
// loaders live in lib/loaders.ts (server-only). The question bank is static and
// generated by scripts/extract_question_bank.py; the app never writes it.

import type { Letter, Part, Part5, Part6Or7, Question, ReadingTest } from "./types";

/** All questions of a test, flattened into number order. */
export function flattenQuestions(test: ReadingTest): Question[] {
  return test.parts.flatMap((p) =>
    p.part === 5 ? p.questions : p.passages.flatMap((ps) => ps.questions),
  );
}

export function part5(part: Part): part is Part5 {
  return part.part === 5;
}

export function part6Or7(part: Part): part is Part6Or7 {
  return part.part === 6 || part.part === 7;
}

/** Compact summary used by the test list. */
export interface TestSummary {
  testId: string;
  title: string;
  verified: boolean;
  counts: { 5: number; 6: number; 7: number };
}

export function summarise(test: ReadingTest): TestSummary {
  const counts = { 5: 0, 6: 0, 7: 0 };
  for (const p of test.parts) {
    const n = p.part === 5 ? p.questions.length : p.passages.reduce((a, ps) => a + ps.questions.length, 0);
    counts[p.part] = n;
  }
  return { testId: test.testId, title: test.title, verified: test.verified, counts };
}

// ---- client payloads ----

export interface ClientQuestion {
  number: number;
  stem: string;
  options: Record<Letter, string>;
  part: 5 | 6 | 7;
  /** Present in practice, intentionally absent in timed (no peeking). */
  answer?: Letter;
  translation?: string;
  explanation?: string;
}

export interface ClientPassageSet {
  descriptor: string;
  title: string;
  text: string;
  questions: ClientQuestion[];
}

export interface ClientTest {
  testId: string;
  title: string;
  verified: boolean;
  parts: Array<
    | { part: 5; questions: ClientQuestion[] }
    | { part: 6 | 7; passages: ClientPassageSet[] }
  >;
}

function toClientQuestion(q: Question, part: 5 | 6 | 7, reveal: boolean): ClientQuestion {
  return reveal
    ? { ...q, part }
    : { number: q.number, stem: q.stem, options: q.options, part };
}

/** Build the client payload. `reveal=false` (timed) strips answers/explanations. */
export function toClientTest(test: ReadingTest, reveal: boolean): ClientTest {
  return {
    testId: test.testId,
    title: test.title,
    verified: test.verified,
    parts: test.parts.map((p) =>
      p.part === 5
        ? { part: 5 as const, questions: p.questions.map((q) => toClientQuestion(q, 5, reveal)) }
        : {
            part: p.part,
            passages: p.passages.map((ps) => ({
              descriptor: ps.descriptor,
              title: ps.title,
              text: ps.text,
              questions: ps.questions.map((q) => toClientQuestion(q, p.part, reveal)),
            })),
          },
    ),
  };
}

export interface FlatItem {
  question: ClientQuestion;
  passage: { title: string; text: string; descriptor: string } | null;
  showPassage: boolean; // true on the first question of a passage set
}

/** Flatten a client test into a single ordered, navigable list. */
export function flattenClientTest(test: ClientTest): FlatItem[] {
  const items: FlatItem[] = [];
  for (const p of test.parts) {
    if (p.part === 5) {
      for (const q of p.questions) items.push({ question: q, passage: null, showPassage: false });
    } else {
      for (const ps of p.passages) {
        ps.questions.forEach((q, i) =>
          items.push({
            question: q,
            passage: { title: ps.title, text: ps.text, descriptor: ps.descriptor },
            showPassage: i === 0,
          }),
        );
      }
    }
  }
  return items;
}
